coverage:
  precision: 2
  round: down
  range: "60..75"
  notify:
  # notification blocks. See: https://docs.codecov.io/docs/codecovyml-reference#section-coverage-notify
  status:
    project:
      default: # default is the status check's name, not default settings
        target: auto
        threshold: "5"

parsers:
  go:
    partials_as_hits: false
